server:
  port: 8083

spring:
  application:
    name: rabbitmq
  datasource:
    url: jdbc:postgresql://localhost:5435/rabbitmq_history_data
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queueSecurity: queueSecurity
    queueEnglishData: queueEnglishData

