server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: security-route
          uri: lb://security-service
          predicates:
            - Path=/auth/**

        - id: simple-english-data
          uri: lb://simple-english-data
          predicates:
            - Path=/simple-english/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true



