server:
  port: 8081

jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==

spring:
  application:
    name: security
  profiles:
    active: security
  datasource:
    url: jdbc:postgresql://localhost:5432/learningEnglish_data
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    salt: $2a$10$DPI5EEuPpcGWKF1wsfp9Qe
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchangeSecurity: exchangeSecurity
    queueSecurity: queueSecurity
    routingkeySecurity: routingkeySecurity

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka
  instance:
    prefer-ip-address: true
