apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: security
  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
        - name: security
          image: ravenhub/security-server:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APPLICATION_NAME
              value: "security-service"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server-service:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://my-release-postgresql-primary:5432/learningEnglish_data"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
            - name: JWT_SECRET_ACCESS
              value: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
            - name: JWT_SECRET_REFRESH
              value: "zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg=="
---
apiVersion: v1
kind: Service
metadata:
  name: security-service
spec:
  type: ClusterIP
  selector:
    app: security
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081