apiVersion: v1
kind: ServiceAccount
metadata:
  name: eureka-full-access
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eureka-full-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eureka-full-role-binding
subjects:
  - kind: ServiceAccount
    name: eureka-full-access
    namespace: default
roleRef:
  kind: ClusterRole
  name: eureka-full-role
  apiGroup: rbac.authorization.k8s.io